const avatars: { [key: string]: any } = {
    Z1: require("../assets/images/avatars/Z1.png"),
    Z2: require("../assets/images/avatars/Z2.png"),
    Z3: require("../assets/images/avatars/Z3.png"),
    Z4: require("../assets/images/avatars/Z4.png"),
    Z5: require("../assets/images/avatars/Z5.png"),
    Z6: require("../assets/images/avatars/Z6.png"),
    Z7: require("../assets/images/avatars/Z7.png"),
    Z8: require("../assets/images/avatars/Z8.png"),
    Z9: require("../assets/images/avatars/Z9.png"),
    Z10: require("../assets/images/avatars/Z10.png"),
    Z11: require("../assets/images/avatars/Z11.png"),
    Z12: require("../assets/images/avatars/Z12.png"),
    Z13: require("../assets/images/avatars/Z13.png"),
    Z14: require("../assets/images/avatars/Z14.png"),
    Z15: require("../assets/images/avatars/Z15.png"),
    Z16: require("../assets/images/avatars/Z16.png"),
    Z17: require("../assets/images/avatars/Z17.png"),
    Z18: require("../assets/images/avatars/Z18.png"),
    Z19: require("../assets/images/avatars/Z19.png"),
    Z20: require("../assets/images/avatars/Z20.png"),
    Z21: require("../assets/images/avatars/Z21.png"),
    Z22: require("../assets/images/avatars/Z22.png"),
    Z23: require("../assets/images/avatars/Z23.png"),
    Z24: require("../assets/images/avatars/Z24.png"),
    Z25: require("../assets/images/avatars/Z25.png"),
    Z26: require("../assets/images/avatars/Z26.png"),
    Z27: require("../assets/images/avatars/Z27.png"),
    Z28: require("../assets/images/avatars/Z28.png"),
    Z29: require("../assets/images/avatars/Z29.png"),
    Z30: require("../assets/images/avatars/Z30.png"),
    Z31: require("../assets/images/avatars/Z31.png"),
    Z32: require("../assets/images/avatars/Z32.png"),
    Z33: require("../assets/images/avatars/Z33.png"),
    Z34: require("../assets/images/avatars/Z34.png"),
    Z35: require("../assets/images/avatars/Z35.png"),
    Z36: require("../assets/images/avatars/Z36.png"),
    Z37: require("../assets/images/avatars/Z37.png"),
    Z38: require("../assets/images/avatars/Z38.png"),
    Z39: require("../assets/images/avatars/Z39.png"),
    Z40: require("../assets/images/avatars/Z40.png"),
    Z41: require("../assets/images/avatars/Z41.png"),
    Z42: require("../assets/images/avatars/Z42.png"),
    Z43: require("../assets/images/avatars/Z43.png"),
    Z44: require("../assets/images/avatars/Z44.png"),
    Z45: require("../assets/images/avatars/Z45.png"),
    Z46: require("../assets/images/avatars/Z46.png"),
    Z47: require("../assets/images/avatars/Z47.png"),
  };
  
  export default avatars;
  